
//This convenience header imports the other headers in the library.

#import "AudioJackReaderType.h"
#import "CardReaderAutodetectResult.h"
#import "PGAccessoryController.h"
#import "PGAudioJackConnectionDetectorDelegate.h"
#import "PGAudioJackConnectionDetector.h"
#import "PGAudioJackCardReaderTypeDetector.h"
#import "PGCard.h"
#import "PGEncrypt.h"
#import "PGEncryptedSwipedCard.h"
#import "PGKeyedCard.h"
#import "PGMagnesafeSwipedCard.h"
#import "PGSwipeController.h"
#import "PGSwipedCard.h"
#import "PGSwipeDelegate.h"
#import "PGSwipeDevice.h"
#import "PGSwipeIDynamo.h"
#import "PGSwipeIpsEnterprise.h"
#import "PGSwipeIps.h"
#import "PGSwipeUnimag.h"
#import "PGSwipeUniMagMessageOptions.h"
#import "SwipeActivationResult.h"
#import "SwipeReasonUnreadyForSwipe.h"
